### ISSUE TITLE
Uncaught exception when calling resetexperiment

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#52]
Calling resetexperiment with the correct id and key like so:

`http://strm.mnds.org:7070/exp/1318627cc5/resetexperiment?key=179229b360`

leads to the an uncaught exception "name 'Experiment' is not defined":

```
ERROR:tornado.application:Uncaught exception GET /exp/1318627cc5/resetexperiment?key=179229b360 (83.84.150.141)
HTTPServerRequest(protocol='http', host='strm.mnds.org:7070', method='GET', uri='/exp/1318627cc5/resetexperiment?key=179229b360', version='HTTP/1.1', remote
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/test/streamingbandit/app/handlers/adminhandlers.py", line 302, in get
    __EXP__ = Experiment(exp_id, key)
NameError: name 'Experiment' is not defined

```

**Comment by g0ulash** [comment]
Fixed in c3055c2
