### ISSUE TITLE
Error when logging in with unknown user; is this ok?

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#54]
ERROR:tornado.application:Uncaught exception POST /login (::1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/login', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept': '*/*', 'Content-Length': '39', 'Connection': 'keep-alive', 'Origin': 'null', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:44.0) Gecko/20100101 Firefox/44.0', 'Host': 'localhost:8080', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/json'})
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/mauritskate/Documents/work/_GIT/STREAMINGBANDIT/streamingbandit/app/handlers/loginhandlers.py", line 31, in post
    users = Users()
  File "/Users/mauritskate/Documents/work/_GIT/STREAMINGBANDIT/streamingbandit/app/db/users.py", line 10, in __init__
    f = open("config.cfg", 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'config.cfg'

**Comment by g0ulash** [comment]
This is because you're not running streamingbandit from the actual folder. So do:

```
cd /path/to/streamingbandit/app
python3 ./app.py
```

**Comment by MKaptein** [comment]
Correct! This actually solved the issue!
