### ISSUE TITLE
New Redis issue

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#76]
There is an issue with setting an experiment with the newest version of Redis, we get back this error:

error | {…}
-- | --
code | 500
traceback | […]
0 | Traceback (most recent call last):
1 | File "/home/parva/.local/lib/python3.5/site-packages/tornado/web.py", line 1590, in _execute     result = method(*self.path_args, **self.path_kwargs)
2 | File "/home/parva/streamingbandit/app/handlers/adminhandlers.py", line 116, in post     insertid = db.insert_experiment(exp_obj)
3 | File "/home/parva/streamingbandit/app/db/database.py", line 137, in insert_experiment     self.r_server.hmset("exp:%s:properties" % exp_id, obj)
4 | File "/home/parva/.local/lib/python3.5/site-packages/redis/client.py", line 2636, in hmset     return self.execute_command('HMSET', name, *items)
5 | File "/home/parva/.local/lib/python3.5/site-packages/redis/client.py", line 754, in execute_command     connection.send_command(*args)
6 | File "/home/parva/.local/lib/python3.5/site-packages/redis/connection.py", line 619, in send_command     self.send_packed_command(self.pack_command(*args))
7 | File "/home/parva/.local/lib/python3.5/site-packages/redis/connection.py", line 659, in pack_command     for arg in imap(self.encoder.encode, args):
8 | File "/home/parva/.local/lib/python3.5/site-packages/redis/connection.py", line 113, in encode     raise DataError("Invalid input of type: 'bool'. Convert to a "
9 | redis.exceptions.DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.
message | Internal Server Error

Apparently this is related to this commit of Redis:

https://github.com/andymccurdy/redis-py/commit/40025ae073f7b376b496a54491fbb30d964dcb24

We can fix this by changing the following code to go from Bool to String.

https://github.com/Nth-iteration-labs/streamingbandit/blob/5d25d8a5568eca83d061e9fe8772c406634caae5/app/handlers/adminhandlers.py#L102-L106

and

https://github.com/Nth-iteration-labs/streamingbandit/blob/5d25d8a5568eca83d061e9fe8772c406634caae5/app/handlers/adminhandlers.py#L237-L241

**Comment by g0ulash** [comment]
Fixed by 2435e7d.
